// dummydata.ts
export const animalData = {
  dog: [
    {
      id: '1',
      profilePic: '/dogcategory.png',
      images: [],
      name: 'Damian',
      breed: 'Golden Retriever',
      old: '2',
      gender: 'Male',
      bgColor: 'bg-[#d54746]',
      distance: 3.1,
      health: [],
      nutrition: [],
    },
    {
      id: '2',
      profilePic: '/pitbull.png',
      images: [],
      name: 'Sparky',
      breed: 'Pitbull',
      old: '8',
      gender: 'Female',
      distance: 2.5,
      bgColor: 'bg-[#d54746]',
      health: [],
      nutrition: [],
    },
    {
      id: '3',
      profilePic: '/husky.png',
      images: ['/husky2.png', '/husyk3.png'],
      name: 'Max',
      breed: 'Siberian Husky',
      old: '5',
      gender: 'Male',
      distance: 1.8,
      bgColor: 'bg-[#d54746]',
      health: [
        { text: 'Up-to-date on vaccinations', type: 'good' },
        { text: 'Parasite clean', type: 'good' },
        { text: 'No history of surgery', type: 'good' },
        { text: 'Allergic to household chemicals and cleaning products', type: 'bad' },
      ],
      nutrition: [
        { text: 'High-quality dry kibble', type: 'good' },
        { text: 'High-protein diets (chicken, beef, lamb)', type: 'good' },
        { text: 'Raw food diets (with proper balance and veterinary guidance)', type: 'good' },
        { text: 'Fresh vegetables (carrots, peas, green beans)', type: 'good' },
        { text: 'Bones', type: 'bad' },
        { text: 'Chocolate', type: 'bad' },
        { text: 'Fatty and fried foods', type: 'bad' },
      ],
    },
    {
      id: '4',
      profilePic: '/zoe.png',
      images: [],
      name: 'Zoe',
      breed: 'Nu se stie',
      old: '10',
      gender: 'Male',
      distance: 3.9,
      bgColor: 'bg-[#d54746]',
      health: [],
      nutrition: [],
    },
  ],
  cat: [
    {
      id: '5',
      images: ['/catcategory.png', '/cat2.png'],
      name: 'Whiskers',
      breed: 'Siamese',
      old: '3',
      gender: 'Male',
      distance: 1.2,
    },
    {
      id: '6',
      images: ['/catcategory.png', '/cat3.png'],
      name: 'Shadow',
      breed: 'Persian',
      old: '5',
      gender: 'Female',
      distance: 0.9,
    },
  ],
  // Add other categories as needed
}
